# Listado de todos los paquetes que de instalan al ejecutar el programa.

ENVIROMENT=(
	waybar
	foot
	mako-notifier
	libnotify-bin
	gnome-keyring
	lxpolkit
	pinentry-gnome3
)

SOUND=(
	pipewire
	wireplumber
	pavucontrol
)

MULTIMEDIA=(
	mpv
	brightnessctl
	swayimg
	zathura
	zathura-pdf-poppler
	gammastep
)

THEME=(
	arc-theme
	papirus-icon-theme
	breeze-cursor-theme
	fonts-firacode
)

EXTRA=(
	lf
	chafa # visualizar imágenes en lf.
	poppler-utils # visualizar pdfs en lf.
	udisks2
	udiskie
	p7zip-full # sustituye a las demás herramientas de compresión.
	curl
	network-manager
	fastfetch
	pass
	pass-otp
	neovim
	htop
	gh
	fzf
	libfuse2t64 # dependencia para appimages
	trash-cli
	jq
	transmission
	plymouth
	plymouth-themes
)
